commands:
  no-permission: "§6Gradient Block §7>> §cYou do not have permission to use this command."
  need-player: "§6Gradient Block §7>> §cYou must be a player to use this command."

gui:
  title: "§6Gradient Block"
  item-name: ""
  item-type: "BLACK_STAINED_GLASS"