name: GradientBlock
version: '${project.version}'
main: dev.twme.gradientblock.GradientBlock
api-version: '1.20'
depend:
  - FastAsyncWorldEdit
authors:
  - TWME
website: "https://github.com/TWME-TW/GradientBlock"
description: "An architect's tool that can generate a gradient-colored block arrangement using two blocks."
commands:
  gradientblock:
    description: "Opens the GradientBlock GUI."
    usage: /<command>
    aliases:
      - gb
    permission: gradientblock.use
    permission-message: "You don't have permission to use this command."
    tab-completions:
      - gradientblock
      - gb
      - gblock
permissions:
  gradientblock.use:
    description: "Allows you to use the GradientBlock GUI."
    default: true
