name: GradientBlock
version: '${project.version}'
main: dev.twme.gradientblock.GradientBlock
api-version: '1.20'
depend:
  - FastAsyncWorldEdit
authors:
  - TWME
description: A plugin that allows you to create blocks with a gradient.
commands:
  gradientblock:
    description: Opens the GradientBlock GUI.
    usage: /<command> [reload]
    aliases:
      - gb
    permission: gradientblock.use
    permission-message: You don't have permission to use this command.
    tab-completions:
      - gradientblock
      - gb
      - gblock
